trigger: none

variables:
  - template: '../templates/variables/init_variables.yaml'
  
stages:
- template: '../templates/stages/bicep_main_infra[single-stage].yaml'
  parameters:
    envShortDisplayName: ${{variables.envShortDisplayName }}
    stageDepOn: ''